server:
    port: 8080
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cbs?useUnicode=true&characterEncoding=utf8&useSSL=false
      password: root123
      username: root
    jpa:
      database: MySQL
      generate-ddl: true

    redis:
      database: 0
      host: 127.0.0.1
      port: 6379


mybatis:
      type-aliases-package: com.qf.pojo
      mapper-locations: classpath:mapper/*Mapper.xml